/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project.unn.lab_java;
import Timer.Timer;
import Timer.TimerIterator;
/**
 *
 * @author nniks
 */
public class ClientJPanel extends javax.swing.JPanel {
//    Timer timer = new Timer();
//    TimerIterator iterator = new TimerIterator(timer);
//    public int hour;
//    public int minute;
//    public int second;
    /**
     * Creates new form JPanelApp
     */
    public ClientJPanel() {
        initComponents();
    }
//    public void set_time(int sph, int spm, int sps) throws Exception { timer.set_time(sph, spm, sps);}
//    public void run() { iterator.run();}
//    public int get_hour() { return timer.get_hour(); }
//    public int get_minute() { return timer.get_minute(); }
//    public int get_second() { return timer.get_minute(); }
//    public int[] get_time(){ return iterator.get_time(); }
//    public void diff_time(int _hour, int minute, int _second){
//        
//    }
//    public String time_string(){
//        String s = "";
//        if(timer.get_hour() < 10){
//            s += "0";
//        }
//        s += timer.get_hour() + ":";
//        if(timer.get_minute() < 10){
//            s += "0";
//        }
//        s += timer.get_minute() + ":";
//        if(timer.get_second() < 10){
//            s += "0";
//        }
//        s += timer.get_second(); 
//        return s;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
